package com.javajedis.legalconnect.scheduling;

public enum ScheduleType {
    MEETING,
    COURT_HEARING,
    DOCUMENT_SUBMISSION_DEADLINE,
    PAYMENT_DUE_DATE,
    FOLLOW_UP_CALL,
    MEDIATION_SESSION,
    ARBITRATION_SESSION,
    LEGAL_NOTICE_RESPONSE_DEADLINE,
    CONTRACT_SIGNING,
    DISCOVERY_DATE,
    DEPOSITION_DATE,
    EVIDENCE_COLLECTION_REMINDER,
    LEGAL_ADVICE_SESSION,
    BAIL_HEARING,
    PROBATION_MEETING,
    PAROLE_MEETING,
    COMPLIANCE_DEADLINE
} 